Improved: AssetMaint - Move from hard-coded menu location to parameterized (OFBIZ-12952) (#94)
Fixes a "typo"

But that's not enough I also get:
|E| Error rendering included menu named [MainActionMenu] at location
[component://assetmaint/widget/AssetmaintMenus.xml]:
java.lang.IllegalArgumentException: Could not find menu with name
[MainActionMenu] in location [component://assetmaint/widget/AssetmaintMenus.xml]

Just have to get assetmaint/control/main

Better test before creating PRs :/